"""chemagent.explainability.counterfactual_tools
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
MCP tool functions for counterfactual molecular generation.

Registered via ``_register()`` in ``chemagent_mcp.py``.

Functions
---------
generate_counterfactuals  — generate counterfactuals for all compounds in a split
visualize_counterfactuals — draw query + counterfactuals as a molecule grid image

Counterfactuals are structurally similar molecules that the model predicts differently
from the query compound.  They are generated by:
1. Collecting all unique SMILES from both train and test splits.
2. Running CCR fragmentation on the entire set to extract molecular cores.
3. Substituting attachment points with a library of R-groups.
4. Filtering analogs for which the model prediction changes from the query's class.
5. Mapping each CF back to query compounds that share the core it was derived from.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any, List, Optional

import joblib
from rdkit import Chem
from rdkit.Chem import Draw
from mcp.server.fastmcp import Image as MCPImage

_SRC = Path(__file__).resolve().parents[2]
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from chemagent.session_utils import get_session_logger as _get_session_logger


def _core_to_substructure_query(core_smiles: str) -> Optional[Chem.Mol]:
    """Convert a CCR core SMILES with [*:N] attachment points to a SMARTS query."""
    smarts = re.sub(r'\[\*:\d+\]', '[*]', core_smiles)
    return Chem.MolFromSmarts(smarts)


def generate_counterfactuals(
    split_file_path: str,
    model_path: str,
    target_class: int = 1,
    n_bits: int = 2048,
    radius: int = 2,
    max_cfs_per_compound: int = 10,
    use_multiple_substituents: bool = False,
    max_mw_change: Optional[float] = None,
    seed: int = 2023,
) -> dict[str, Any]:
    """Generate counterfactual molecules for all compounds in a dataset split.

    Runs CCR fragmentation on **all** unique SMILES from the train and test splits
    simultaneously to build a richer core library.  Each generated CF is then
    associated with every query compound whose structure contains the same core
    (substructure match), so each compound receives only structurally relevant CFs.

    Parameters
    ----------
    split_file_path : str
        Path to the split .pkl file (from split_dataset).  Must contain
        ``train_smiles`` and/or ``test_smiles`` keys.
    model_path : str
        Path to the trained sklearn model file (.pkl format).
    target_class : int, optional
        Predicted class of the query compounds — counterfactuals will have a
        *different* predicted class (default 1).
    n_bits : int, optional
        ECFP fingerprint length in bits (default 2048).  Must match the model's
        training fingerprints.
    radius : int, optional
        ECFP Morgan radius (default 2, i.e. ECFP4).  Must match training setup.
    max_cfs_per_compound : int, optional
        Maximum number of counterfactuals to keep per query compound (default 10).
    use_multiple_substituents : bool, optional
        If True, also try pairs of substituents on cores with two attachment points
        (default False).  Significantly increases computation time.
    max_mw_change : float, optional
        If set, only keep CFs whose molecular weight differs from the core by at
        most this many Da (default None = no filter).
    seed : int, optional
        Random seed for reproducibility (default 2023).

    Returns
    -------
    dict
        - num_total_smiles: number of unique SMILES used for CF generation
        - num_cfs_found: total number of CFs generated before per-compound limiting
        - num_compounds_with_cfs: number of query compounds that received at least one CF
        - results_by_compound: dict mapping query SMILES → compound result dict:
            - smiles: query SMILES
            - counterfactuals: list of CF dicts, each with:
                - cf_smiles: SMILES of the counterfactual
                - predicted_class: model's predicted class for the CF
                - confidence: prediction probability for the CF's predicted class
                - mw_change: MW difference vs the core scaffold (Da)
                - core_smiles: CCR core scaffold this CF was derived from
            - num_cfs: number of CFs for this compound
        - status: "completed" or "no_counterfactuals_found"

    Raises
    ------
    ValueError
        If the split file or model cannot be loaded, or if CCR analysis fails.

    Examples
    --------
    >>> result = generate_counterfactuals(
    ...     split_file_path="data/logs/session_xxx/splits/data_random.pkl",
    ...     model_path="data/logs/session_xxx/models/data_RFC.pkl",
    ...     target_class=1,
    ... )
    >>> for smiles, compound in result["results_by_compound"].items():
    ...     print(smiles, "→", compound["num_cfs"], "CFs")
    ...     for cf in compound["counterfactuals"]:
    ...         print("  ", cf["cf_smiles"], "class", cf["predicted_class"])
    """
    logger = _get_session_logger()

    # Load split file
    try:
        split_data = joblib.load(split_file_path)
    except Exception as e:
        raise ValueError(f"Failed to load split file from {split_file_path}: {e}")

    # Collect all unique SMILES from train + test
    all_smiles: list[str] = []
    for split in ("train", "test"):
        key = f"{split}_smiles"
        if key in split_data:
            all_smiles.extend(split_data[key])

    # Deduplicate while preserving order
    seen: set[str] = set()
    unique_smiles: list[str] = []
    for s in all_smiles:
        if s and s not in seen:
            seen.add(s)
            unique_smiles.append(s)

    if not unique_smiles:
        raise ValueError("No SMILES found in train or test splits of the split file.")

    # Load model
    try:
        model = joblib.load(model_path)
    except Exception as e:
        raise ValueError(f"Failed to load model from {model_path}: {e}")

    # Run CFGenerator on ALL unique SMILES at once
    from chemagent.explainability.Counterfactuals.CF_generator_v2 import CFGenerator

    try:
        cf_gen = CFGenerator(
            smiles_lst=unique_smiles,
            model_obj=model,
            n_bits=n_bits,
            radius=radius,
            random_seed=seed,
            base_class=target_class,
            use_multiple_substituents=use_multiple_substituents,
            num_classes=2,
        )
        cf_df = cf_gen.find_cfs()
    except Exception as e:
        raise ValueError(f"Counterfactual generation failed: {e}")

    if cf_df.empty:
        return {
            "num_total_smiles": len(unique_smiles),
            "num_cfs_found": 0,
            "num_compounds_with_cfs": 0,
            "results_by_compound": {},
            "status": "no_counterfactuals_found",
        }

    # Optional MW filter
    if max_mw_change is not None:
        cf_df = cf_df.loc[cf_df["change_MW"].abs() <= max_mw_change].reset_index(drop=True)

    # Parse all input molecules once for substructure matching
    input_mols: dict[str, Optional[Chem.Mol]] = {
        smi: Chem.MolFromSmiles(smi) for smi in unique_smiles
    }

    # Map each CF to query compounds that share its core via substructure match
    results_by_compound: dict[str, dict] = {}

    for _, row in cf_df.iterrows():
        core_smiles = str(row.get("core_smiles", ""))
        query_mol = _core_to_substructure_query(core_smiles) if core_smiles else None

        predicted_class = int(row["Predicted"])
        conf: Optional[float] = None
        if f"proba_class_{predicted_class}" in row.index:
            conf = float(row[f"proba_class_{predicted_class}"])

        cf_entry = {
            "cf_smiles": row["CF_smiles"],
            "predicted_class": predicted_class,
            "confidence": conf,
            "mw_change": float(row.get("change_MW", 0.0)),
            "core_smiles": core_smiles,
        }

        # Associate this CF with every input compound that contains the core
        if query_mol is not None:
            for smi, mol in input_mols.items():
                if mol is not None and mol.HasSubstructMatch(query_mol):
                    if smi not in results_by_compound:
                        results_by_compound[smi] = {"smiles": smi, "counterfactuals": []}
                    results_by_compound[smi]["counterfactuals"].append(cf_entry)

    # Trim to max_cfs_per_compound and add count
    for compound_result in results_by_compound.values():
        compound_result["counterfactuals"] = compound_result["counterfactuals"][:max_cfs_per_compound]
        compound_result["num_cfs"] = len(compound_result["counterfactuals"])

    return {
        "num_total_smiles": len(unique_smiles),
        "num_cfs_found": len(cf_df),
        "num_compounds_with_cfs": len(results_by_compound),
        "results_by_compound": results_by_compound,
        "status": "completed",
    }


def visualize_counterfactuals(
    query_smiles: str,
    cf_smiles_list: List[str],
    output_path: Optional[str] = None,
    mol_size: tuple[int, int] = (300, 300),
    mols_per_row: int = 4,
) -> dict[str, Any]:
    """Draw the query compound and its counterfactuals as a molecule grid image.

    Parameters
    ----------
    query_smiles : str
        SMILES of the original query compound.
    cf_smiles_list : list[str]
        SMILES of the counterfactual compounds to display.
    output_path : str, optional
        Path to save the image (.png).  Defaults to the session plots directory.
    mol_size : tuple[int, int], optional
        Pixel size of each molecule cell in the grid (default (300, 300)).
    mols_per_row : int, optional
        Number of molecules per row in the grid (default 4).

    Returns
    -------
    dict
        - image: MCP Image object that renders directly in the LM Studio chat
        - image_path: path to the saved PNG file
        - num_counterfactuals: number of CFs included in the image
        - status: completion status

    Raises
    ------
    ValueError
        If the query SMILES is invalid.

    Examples
    --------
    >>> result = generate_counterfactuals(
    ...     split_file_path="data/logs/session_xxx/splits/data.pkl",
    ...     model_path="data/logs/session_xxx/models/model.pkl",
    ... )
    >>> # Pick one query compound and visualize its CFs
    >>> query = next(iter(result["results_by_compound"]))
    >>> viz = visualize_counterfactuals(
    ...     query_smiles=query,
    ...     cf_smiles_list=[c["cf_smiles"] for c in result["results_by_compound"][query]["counterfactuals"]],
    ... )
    """
    logger = _get_session_logger()

    query_mol = Chem.MolFromSmiles(query_smiles)
    if query_mol is None:
        raise ValueError(f"Invalid query SMILES: {query_smiles}")

    cf_mols = []
    cf_legends = []
    for i, smi in enumerate(cf_smiles_list):
        m = Chem.MolFromSmiles(smi)
        if m is not None:
            cf_mols.append(m)
            cf_legends.append(f"CF {i + 1}")

    all_mols = [query_mol] + cf_mols
    all_legends = ["Query (original)"] + cf_legends

    img = Draw.MolsToGridImage(
        all_mols,
        molsPerRow=mols_per_row,
        subImgSize=mol_size,
        legends=all_legends,
    )

    if output_path is None:
        output_path = logger.session_dir / "plots" / f"counterfactuals_{logger.session_id}.png"
    else:
        output_path = Path(output_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(str(output_path))

    mcp_image = MCPImage(path=output_path)

    metadata = {
        "image_path": str(output_path),
        "num_counterfactuals": len(cf_mols),
        "status": "completed",
    }
    # Return as a list so fastmcp emits an ImageContent block + a TextContent block.
    # Returning MCPImage nested inside a dict causes a serialization error.
    return [mcp_image, json.dumps(metadata, indent=2)]
